version: "3.5"

services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - default
  api:
    image: node:10-alpine
    links:
      - redis
    working_dir: /app
    depends_on:
      - redis
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: npm start
    networks:
      - default
  test:
    image: node:10-alpine
    volumes:
      - ./src:/app/src
      - ./coverage/unit:/app/coverage
    container_name: api_test
    entrypoint: ["npm", "test"]
networks:
  default:
    name: api-network
